-- MySQL Script generated by MySQL Workbench
-- Wed Jun  2 07:08:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pima_cpt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pima_cpt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pima_cpt` DEFAULT CHARACTER SET utf8 ;
USE `pima_cpt` ;

-- -----------------------------------------------------
-- Table `pima_cpt`.`category_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`category_user` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `pima_cpt`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `categoria` INT NOT NULL,
  INDEX `categoriauser_idx` (`categoria` ASC) ,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`user_name` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  CONSTRAINT `categoriauser`
    FOREIGN KEY (`categoria`)
    REFERENCES `pima_cpt`.`category_user` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pima_cpt`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `idestado_UNIQUE` (`idestado` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(65) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`),
  UNIQUE INDEX `idmunicipio_UNIQUE` (`idmunicipio` ASC) ,
  INDEX `estadoMunicipio_idx` (`estado` ASC) ,
  CONSTRAINT `estadoMunicipio`
    FOREIGN KEY (`estado`)
    REFERENCES `pima_cpt`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`colonia` (
  `idcolonia` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(65) NOT NULL,
  `cp` VARCHAR(7) NOT NULL,
  `municipio` INT NOT NULL,
  PRIMARY KEY (`idcolonia`),
  UNIQUE INDEX `idcolonia_UNIQUE` (`idcolonia` ASC) ,
  INDEX `municipioColonia_idx` (`municipio` ASC) ,
  CONSTRAINT `municipioColonia`
    FOREIGN KEY (`municipio`)
    REFERENCES `pima_cpt`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`broker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`broker` (
  `id_broker` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `paterno` VARCHAR(150) NOT NULL,
  `materno` VARCHAR(150) NOT NULL,
  `calle` VARCHAR(65) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `interior` VARCHAR(15) NOT NULL,
  `user` INT NOT NULL AUTO_INCREMENT,
  `colonia` INT NOT NULL,
  PRIMARY KEY (`id_broker`),
  UNIQUE INDEX `idasesor_UNIQUE` (`id_broker` ASC) ,
  INDEX `userconect_idx` (`user` ASC) ,
  INDEX `coloniaAsesor_idx` (`colonia` ASC) ,
  CONSTRAINT `userconect`
    FOREIGN KEY (`user`)
    REFERENCES `pima_cpt`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coloniaAsesor`
    FOREIGN KEY (`colonia`)
    REFERENCES `pima_cpt`.`colonia` (`idcolonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`gender` (
  `id_gender` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gender`),
  UNIQUE INDEX `idgender_UNIQUE` (`id_gender` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`nationality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`nationality` (
  `id_nationality` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_nationality`),
  UNIQUE INDEX `idnationality_UNIQUE` (`id_nationality` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`marital_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`marital_status` (
  `id_marital_status` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marital_status`),
  UNIQUE INDEX `idmarital_status_UNIQUE` (`id_marital_status` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_cilvil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_cilvil` (
  `id_type_cilvil` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_cilvil`),
  UNIQUE INDEX `idtype_cilvil_UNIQUE` (`id_type_cilvil` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `paterno` VARCHAR(150) NOT NULL,
  `materno` VARCHAR(150) NOT NULL,
  `street` VARCHAR(65) NOT NULL,
  `number` VARCHAR(15) NOT NULL,
  `interior` VARCHAR(15) NOT NULL,
  `suburb` INT NOT NULL,
  `user` INT NOT NULL,
  `gender` INT NOT NULL,
  `nationality` INT NOT NULL,
  `marital_status` INT NOT NULL,
  `civil_type` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `idcliente_UNIQUE` (`id_client` ASC) ,
  INDEX `prospecctouser_idx` (`user` ASC) ,
  INDEX `coloniaCliente_idx` (`suburb` ASC) ,
  INDEX `generoOrgulloso_idx` (`gender` ASC) ,
  INDEX `nationalityClient_idx` (`nationality` ASC) ,
  INDEX `estadoCivil_idx` (`marital_status` ASC) ,
  INDEX `regimenMatrimonial_idx` (`civil_type` ASC) ,
  CONSTRAINT `prospecctouser`
    FOREIGN KEY (`user`)
    REFERENCES `pima_cpt`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coloniaCliente`
    FOREIGN KEY (`suburb`)
    REFERENCES `pima_cpt`.`colonia` (`idcolonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `generoOrgulloso`
    FOREIGN KEY (`gender`)
    REFERENCES `pima_cpt`.`gender` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nationalityClient`
    FOREIGN KEY (`nationality`)
    REFERENCES `pima_cpt`.`nationality` (`id_nationality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estadoCivil`
    FOREIGN KEY (`marital_status`)
    REFERENCES `pima_cpt`.`marital_status` (`id_marital_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `regimenMatrimonial`
    FOREIGN KEY (`civil_type`)
    REFERENCES `pima_cpt`.`type_cilvil` (`id_type_cilvil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`status_requeriment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`status_requeriment` (
  `id_status_requeriment` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_requeriment`),
  UNIQUE INDEX `idestatusSolicitud_UNIQUE` (`id_status_requeriment` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`requement_client_broker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`requement_client_broker` (
  `id_request` INT NOT NULL AUTO_INCREMENT,
  `started` DATETIME NOT NULL DEFAULT,
  `status` INT NOT NULL,
  `broker` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`id_request`),
  UNIQUE INDEX `idsolicitud_UNIQUE` (`id_request` ASC) ,
  INDEX `asesorSolicitud_idx` (`broker` ASC) ,
  INDEX `clienteSolicitud_idx` (`client` ASC) ,
  INDEX `estatusSolicitud_idx` (`status` ASC) ,
  CONSTRAINT `asesorSolicitud`
    FOREIGN KEY (`broker`)
    REFERENCES `pima_cpt`.`broker` (`id_broker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clienteSolicitud`
    FOREIGN KEY (`client`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estatusSolicitud`
    FOREIGN KEY (`status`)
    REFERENCES `pima_cpt`.`status_requeriment` (`id_status_requeriment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`requerement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`requerement` (
  `id_requerement` INT NOT NULL AUTO_INCREMENT,
  `request_m_m` INT NOT NULL,
  PRIMARY KEY (`id_requerement`),
  UNIQUE INDEX `idsolicitud_UNIQUE` (`id_requerement` ASC) ,
  INDEX `solicitudIniciada_idx` (`request_m_m` ASC) ,
  CONSTRAINT `solicitudIniciada`
    FOREIGN KEY (`request_m_m`)
    REFERENCES `pima_cpt`.`requement_client_broker` (`id_request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_document` (
  `id_type_document` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_document`),
  UNIQUE INDEX `idtipoDocumento_UNIQUE` (`id_type_document` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`documentation_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`documentation_cliente` (
  `id_documentacion_cliente` INT NOT NULL AUTO_INCREMENT,
  `document` BLOB NOT NULL,
  `tipo` INT NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id_documentacion_cliente`),
  UNIQUE INDEX `iddocumentacionCliente_UNIQUE` (`id_documentacion_cliente` ASC) ,
  INDEX `clientePropietario_idx` (`cliente` ASC) ,
  INDEX `tipoDocumento_idx` (`tipo` ASC) ,
  CONSTRAINT `clientePropietario`
    FOREIGN KEY (`cliente`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoDocumento`
    FOREIGN KEY (`tipo`)
    REFERENCES `pima_cpt`.`type_document` (`id_type_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_reference` (
  `id_type_reference` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(51) NOT NULL,
  PRIMARY KEY (`id_type_reference`),
  UNIQUE INDEX `idtype_endorsament_UNIQUE` (`id_type_reference` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`reference` (
  `id_reference` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `paterno` VARCHAR(150) NOT NULL,
  `materno` VARCHAR(150) NOT NULL,
  `rfc` VARCHAR(14) NOT NULL,
  `curp` VARCHAR(25) NOT NULL,
  `calle` VARCHAR(65) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `interior` VARCHAR(15) NOT NULL,
  `colonia` INT NOT NULL,
  `client` INT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id_reference`),
  UNIQUE INDEX `idcliente_UNIQUE` (`id_reference` ASC) ,
  INDEX `coloniaCliente_idx` (`colonia` ASC) ,
  INDEX `clienteSolidario_idx` (`client` ASC) ,
  INDEX `tipoRelacionAvan_idx` (`type` ASC) ,
  CONSTRAINT `clienteSolidario`
    FOREIGN KEY (`client`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coloniaSolidario`
    FOREIGN KEY (`colonia`)
    REFERENCES `pima_cpt`.`colonia` (`idcolonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoRelacionAvan`
    FOREIGN KEY (`type`)
    REFERENCES `pima_cpt`.`type_reference` (`id_type_reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`document_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`document_reference` (
  `id_document_reference` INT NOT NULL AUTO_INCREMENT,
  `document` BLOB NOT NULL,
  `type` INT NOT NULL,
  `endorsement` INT NOT NULL,
  PRIMARY KEY (`id_document_reference`),
  UNIQUE INDEX `iddocumentoSolidarion_UNIQUE` (`id_document_reference` ASC) ,
  INDEX `tipoDocumentoSolidario_idx` (`type` ASC) ,
  INDEX `solidarioDSueno_idx` (`endorsement` ASC) ,
  CONSTRAINT `tipoDocumentoSolidario`
    FOREIGN KEY (`type`)
    REFERENCES `pima_cpt`.`type_document` (`id_type_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solidarioDSueno`
    FOREIGN KEY (`endorsement`)
    REFERENCES `pima_cpt`.`reference` (`id_reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`medic_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`medic_questions` (
  `id_medic_questions` INT NOT NULL,
  `question` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_medic_questions`),
  UNIQUE INDEX `idpreguntasMedicas_UNIQUE` (`id_medic_questions` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`option_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`option_answer` (
  `id_option_answer` INT NOT NULL AUTO_INCREMENT,
  `amswer` VARCHAR(255) NOT NULL,
  `question` INT NOT NULL,
  PRIMARY KEY (`id_option_answer`),
  UNIQUE INDEX `idrespuestas_UNIQUE` (`id_option_answer` ASC) ,
  INDEX `opcionMultiple_idx` (`question` ASC) ,
  CONSTRAINT `opcionMultiple`
    FOREIGN KEY (`question`)
    REFERENCES `pima_cpt`.`medic_questions` (`id_medic_questions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`answer_client_opt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`answer_client_opt` (
  `id_answer_client_opt` INT NOT NULL AUTO_INCREMENT,
  `answer_client` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`id_answer_client_opt`),
  UNIQUE INDEX `idrespuestasCliente_UNIQUE` (`id_answer_client_opt` ASC) ,
  INDEX `respuestaOpcionCliente_idx` (`answer_client` ASC) ,
  INDEX `clienteRespuesta_idx` (`client` ASC) ,
  CONSTRAINT `respuestaOpcionCliente`
    FOREIGN KEY (`answer_client`)
    REFERENCES `pima_cpt`.`option_answer` (`id_option_answer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clienteRespuesta`
    FOREIGN KEY (`client`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`free_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`free_answer` (
  `id_free_answer` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NOT NULL,
  `question` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`id_free_answer`),
  UNIQUE INDEX `idrespuestaAbierta_UNIQUE` (`id_free_answer` ASC) ,
  INDEX `respuestaAbiertaPregunta_idx` (`question` ASC) ,
  INDEX `clienteRespAbierta_idx` (`client` ASC) ,
  CONSTRAINT `respuestaAbiertaPregunta`
    FOREIGN KEY (`question`)
    REFERENCES `pima_cpt`.`medic_questions` (`id_medic_questions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clienteRespAbierta`
    FOREIGN KEY (`client`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_datos` (
  `id_tipo_datos` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_datos`),
  UNIQUE INDEX `idtipoDatos_UNIQUE` (`id_tipo_datos` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`personal_data_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`personal_data_client` (
  `id_personal_data_client` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(254) NOT NULL,
  `type_data` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`id_personal_data_client`),
  UNIQUE INDEX `iddatosPersonalesCliente_UNIQUE` (`id_personal_data_client` ASC) ,
  INDEX `clienteDatoPersonal_idx` (`client` ASC) ,
  INDEX `tipoDatoPersonalCliente_idx` (`type_data` ASC) ,
  CONSTRAINT `clienteDatoPersonal`
    FOREIGN KEY (`client`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoDatoPersonalCliente`
    FOREIGN KEY (`type_data`)
    REFERENCES `pima_cpt`.`type_datos` (`id_tipo_datos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`datos_personales_asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`datos_personales_asesor` (
  `id_datos_personales_asesor` INT NOT NULL AUTO_INCREMENT,
  `dato` VARCHAR(254) NOT NULL,
  `tipo_dato` INT NOT NULL,
  `asesor` INT NOT NULL,
  PRIMARY KEY (`id_datos_personales_asesor`),
  UNIQUE INDEX `iddatosPersonalesCliente_UNIQUE` (`id_datos_personales_asesor` ASC) ,
  INDEX `tipoDatoPersonalCliente_idx` (`tipo_dato` ASC) ,
  INDEX `asesorDatoPersonal_idx` (`asesor` ASC) ,
  CONSTRAINT `asesorDatoPersonal`
    FOREIGN KEY (`asesor`)
    REFERENCES `pima_cpt`.`broker` (`id_broker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoDatoPersonalasesor`
    FOREIGN KEY (`tipo_dato`)
    REFERENCES `pima_cpt`.`type_datos` (`id_tipo_datos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_contract` (
  `id_type_contract` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id_type_contract`),
  UNIQUE INDEX `idtype_contract_UNIQUE` (`id_type_contract` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_position` (
  `id_type_position` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id_type_position`),
  UNIQUE INDEX `idtype_position_UNIQUE` (`id_type_position` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`type_laboral_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`type_laboral_activity` (
  `id_type_laboral_activity` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id_type_laboral_activity`),
  UNIQUE INDEX `idtype_laboral_activity_UNIQUE` (`id_type_laboral_activity` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pima_cpt`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pima_cpt`.`work` (
  `id_work` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(128) NOT NULL,
  `calle` VARCHAR(65) NOT NULL,
  `exterior` VARCHAR(15) NOT NULL,
  `interior` VARCHAR(15) NOT NULL,
  `colonia` INT NOT NULL,
  `type_contract` INT NOT NULL,
  `position` INT NOT NULL,
  `laboral_activity` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`id_work`),
  UNIQUE INDEX `idwork_UNIQUE` (`id_work` ASC) ,
  INDEX `coloniatrabajpo_idx` (`colonia` ASC) ,
  INDEX `contratoTipo_idx` (`type_contract` ASC) ,
  INDEX `postitionTypeCliente_idx` (`position` ASC) ,
  INDEX `actividadLaboral_idx` (`laboral_activity` ASC) ,
  INDEX `clientWork_idx` (`client` ASC) ,
  CONSTRAINT `coloniatrabajpo`
    FOREIGN KEY (`colonia`)
    REFERENCES `pima_cpt`.`colonia` (`idcolonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratoTipo`
    FOREIGN KEY (`type_contract`)
    REFERENCES `pima_cpt`.`type_contract` (`id_type_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `postitionTypeCliente`
    FOREIGN KEY (`position`)
    REFERENCES `pima_cpt`.`type_position` (`id_type_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actividadLaboral`
    FOREIGN KEY (`laboral_activity`)
    REFERENCES `pima_cpt`.`type_laboral_activity` (`id_type_laboral_activity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clientWork`
    FOREIGN KEY (`client`)
    REFERENCES `pima_cpt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
